# GODESS_INCLUDE_DIR = godess.h
# GODESS_LIBRARIES = libgodess.so
# GODESS_FOUND = true if cat is found

IF(GODESS_INCLUDE_DIRS)
  FIND_PATH(GODESS_INCLUDE_DIR godess.h  ${GODESS_INCLUDE_DIRS})
  FIND_LIBRARY(GODESS_LIBRARIES godess ${GODESS_LIBRARY_DIRS})
ENDIF(GODESS_INCLUDE_DIRS)


SET(GODESS_FOUND FALSE)
IF(GODESS_INCLUDE_DIR)
  MESSAGE(STATUS "GODESS_INCLUDE_DIR=${GODESS_INCLUDE_DIR}")
  MESSAGE(STATUS "GODESS_LIBRARIES=${GODESS_LIBRARIES}")
  SET(GODESS_FOUND TRUE)
ENDIF(GODESS_INCLUDE_DIR)

MARK_AS_ADVANCED(
   GODESS_INCLUDE_DIR
   GODESS_LIBRARIES
   GODESS_FOUND
)

